#!/usr/bin/env bash
# Script designed for securely moving files from a local client to a remote server
if [ "$#" -lt 4 ]; then
    echo "Please use: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
else
    scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/;
fi

