#!/usr/bin/env bash
# Installs Nginx

apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
# Ensure nginx is listening on port 80 (default)
sed -i 's/.*listen\(.*\)80.*/    listen 80;/g' /etc/nginx/sites-available/default

# Restart nginx without systemctl
kill -s HUP $(pgrep nginx)
