#!/usr/bin/env bash
# Configure Nginx server to handle 404 errors

# Update package lists and install Nginx
apt-get update
apt-get -y install nginx

# Allow Nginx through the firewall and set permissions
ufw allow 'Nginx HTTP'
chmod -R 755 /var/www

# Create a simple 'Hello World' index page
echo 'Hello World' > /var/www/html/index.html

# Nginx server configuration for handling 404 errors
new_config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files \$uri \$uri/ =404;
        }
        error_page 404 /404.html;
        location  /404.html {
            internal;
        }
        if (\$request_filename ~ redirect_me){
            rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        }
}
"

# Create a custom 404 error page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Apply the updated Nginx configuration
echo "$new_config" > /etc/nginx/sites-available/default

# Check if Nginx is running and start or restart accordingly
if ! pgrep nginx > /dev/null; then
    service nginx start
else
    service nginx restart
fi

